name: Bug report
description: Report a problem or regression
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug, expected behavior, and steps to reproduce.
    validations:
      required: true
  - type: input
    id: theme
    attributes:
      label: Theme/folder
      description: If applicable, theme name under smart-input/input
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      render: bash

