import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const canonicalPath = path.join(root, 'canonical', 'theme.json');
const outDir = path.join(root, 'build', 'salla');

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function main() {
  if (!fs.existsSync(canonicalPath)) {
    console.error('Canonical model not found. Run "npm run canonicalize" first.');
    process.exit(1);
  }
  const model = JSON.parse(fs.readFileSync(canonicalPath, 'utf8'));

  ensureDir(outDir);
  ensureDir(path.join(outDir, 'templates'));

  const twig = `<!-- Generated by Beto Factory (Salla) -->
<header>
  <h1>{{ hero.title | default('${model.components?.hero?.props?.title || 'Welcome'}') }}</h1>
  {% if assets.images is defined %}
    {# Example usage of first image if present #}
  {% endif %}
</header>
<main>
  <section class="hero">
    <h2>{{ hero.title | default('Hero') }}</h2>
  </section>
  <section class="product-grid">
    <h2>Products</h2>
  </section>
</main>
<footer>Footer</footer>
`;

  fs.writeFileSync(path.join(outDir, 'templates', 'index.twig'), twig, 'utf8');

  const themeJson = {
    name: 'Beto Theme',
    version: '0.1.0',
    engine: 'twig',
    entry: 'templates/index.twig',
    metadata: { adapter: 'salla' }
  };
  fs.writeFileSync(
    path.join(outDir, 'theme.json'),
    JSON.stringify(themeJson, null, 2),
    'utf8'
  );

  console.log(`✅ Salla adapter output at ${path.relative(root, outDir)}`);
}

main();

