import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const canonicalPath = path.join(root, 'canonical', 'theme.json');
const outDir = path.join(root, 'build', 'salla');

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function main() {
  if (!fs.existsSync(canonicalPath)) {
    console.error('Canonical model not found. Run "npm run canonicalize" first.');
    process.exit(1);
  }
  const model = JSON.parse(fs.readFileSync(canonicalPath, 'utf8'));

  ensureDir(outDir);
  ensureDir(path.join(outDir, 'templates'));

  const defaultHeroTitle = model?.components?.hero?.props?.title || 'Welcome';
  const defaultHeroImage = model?.components?.hero?.props?.image || '';

  const twig = `<!-- Generated by Beto Factory (Salla) -->
<header>
  <h1>{{ hero.title | default('${defaultHeroTitle.replace(/'/g, "''")}') }}</h1>
</header>
<main>
  <section class="hero">
    <h2>{{ hero.title | default('${defaultHeroTitle.replace(/'/g, "''")}') }}</h2>
    {% if hero.image is defined and hero.image %}
      <img src="{{ hero.image }}" alt="Hero" />
    {% else %}
      ${defaultHeroImage ? `<img src="${defaultHeroImage}" alt="Hero" />` : ''}
    {% endif %}
  </section>
  {% if product_grid is defined %}
  <section class="product-grid">
    <h2>Products</h2>
    {# Placeholder for Salla product grid #}
  </section>
  {% endif %}
</main>
<footer>Footer</footer>
`;

  fs.writeFileSync(path.join(outDir, 'templates', 'index.twig'), twig, 'utf8');

  const themeJson = {
    name: 'Beto Theme',
    version: '0.1.0',
    engine: 'twig',
    entry: 'templates/index.twig',
    metadata: { adapter: 'salla' }
  };
  fs.writeFileSync(
    path.join(outDir, 'theme.json'),
    JSON.stringify(themeJson, null, 2),
    'utf8'
  );

  console.log(`✅ Salla adapter output at ${path.relative(root, outDir)}`);
}

main();
