import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const canonicalPath = path.join(root, 'canonical', 'theme.json');
const inputDir = path.join(root, 'input');
const buildDir = path.join(root, 'build', 'salla');

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function copyFileSafe(src, dest) {
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
}

function writeIfMissing(file, content) {
  if (!fs.existsSync(file)) {
    ensureDir(path.dirname(file));
    fs.writeFileSync(file, content, 'utf8');
  }
}

function main() {
  if (!fs.existsSync(canonicalPath)) {
    console.error('Canonical model not found. Run "npm run canonicalize" first.');
    process.exit(1);
  }
  const model = JSON.parse(fs.readFileSync(canonicalPath, 'utf8'));

  // Copy referenced images from input to build assets
  const images = model?.assets?.images || [];
  const copied = [];
  for (const rel of images) {
    const src = path.isAbsolute(rel) ? rel : path.join(inputDir, rel);
    if (fs.existsSync(src)) {
      const dest = path.join(buildDir, 'assets', 'images', path.basename(rel));
      copyFileSafe(src, dest);
      copied.push(dest);
    }
  }

  // Copy any additional assets from input/assets/**/* into build/salla/assets/**/*
  const inputAssetsDir = path.join(inputDir, 'assets');
  let extraCount = 0;
  if (fs.existsSync(inputAssetsDir)) {
    const walk = (dir, relBase = '') => {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const rel = path.join(relBase, entry.name);
        const src = path.join(dir, entry.name);
        const dest = path.join(buildDir, 'assets', rel);
        if (entry.isDirectory()) walk(src, rel);
        else {
          copyFileSafe(src, dest);
          extraCount++;
        }
      }
    };
    walk(inputAssetsDir);
  }

  // Ensure default styles and scripts exist
  writeIfMissing(
    path.join(buildDir, 'assets', 'styles', 'app.css'),
    `/* Generated by Beto Factory */\n:root{--brand:#11224E} body{font-family:system-ui}\n`
  );
  writeIfMissing(
    path.join(buildDir, 'assets', 'js', 'app.js'),
    `// Generated by Beto Factory\nconsole.log('Beto Theme assets loaded');\n`
  );
  writeIfMissing(
    path.join(buildDir, 'assets', 'js', 'product-interaction.js'),
    `// Generated by Beto Factory (interactive stubs)\n(function(){\n  if (typeof Salla !== 'undefined' && Salla.events && Salla.events.on) {\n    Salla.events.on('variant.selected', function(variant){\n      console.log('[Beto] variant selected', variant);\n    });\n  }\n  document.addEventListener('click', function(e){\n    const btn = e.target.closest('.quick-add-btn');\n    if (!btn) return;\n    const id = btn.getAttribute('data-product-id');\n    console.log('[Beto] quick add', id);\n    if (window.Salla && Salla.cart && Salla.cart.add) {\n      Salla.cart.add({id});\n    }\n  });\n})();\n`
  );
  writeIfMissing(
    path.join(buildDir, 'assets', 'styles', 'swatches.css'),
    `.variation-swatches{display:flex;gap:.5rem}.variation-swatches .swatch{padding:.4rem .6rem;border:1px solid #ccc;background:#fff;cursor:pointer}
`
  );

  console.log(`✅ Assets prepared (${copied.length} images, +${extraCount} extra, css/js placeholders)`);
}

main();
