import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const canonicalPath = path.join(root, 'canonical', 'theme.json');
const inputDir = path.join(root, 'input');
const buildDir = path.join(root, 'build', 'salla');

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function copyFileSafe(src, dest) {
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
}

function writeIfMissing(file, content) {
  if (!fs.existsSync(file)) {
    ensureDir(path.dirname(file));
    fs.writeFileSync(file, content, 'utf8');
  }
}

function main() {
  if (!fs.existsSync(canonicalPath)) {
    console.error('Canonical model not found. Run "npm run canonicalize" first.');
    process.exit(1);
  }
  const model = JSON.parse(fs.readFileSync(canonicalPath, 'utf8'));

  // Copy referenced images from input to build assets
  const images = model?.assets?.images || [];
  const copied = [];
  for (const rel of images) {
    const src = path.isAbsolute(rel) ? rel : path.join(inputDir, rel);
    if (fs.existsSync(src)) {
      const dest = path.join(buildDir, 'assets', 'images', path.basename(rel));
      copyFileSafe(src, dest);
      copied.push(dest);
    }
  }

  // Ensure default styles and scripts exist
  writeIfMissing(
    path.join(buildDir, 'assets', 'styles', 'app.css'),
    `/* Generated by Beto Factory */\n:root{--brand:#11224E} body{font-family:system-ui}\n`
  );
  writeIfMissing(
    path.join(buildDir, 'assets', 'js', 'app.js'),
    `// Generated by Beto Factory\nconsole.log('Beto Theme assets loaded');\n`
  );

  console.log(`✅ Assets prepared (${copied.length} images, css/js placeholders)`);
}

main();

